---
- name: set hostname
  lineinfile: dest=/etc/hostname regexp="^.*"  line='{{ inventory_hostname }}'
  notify: reload hostname
  
- name: change ipv4 hosts
  lineinfile: dest=/etc/hosts regexp="^{{ ansible_default_ipv4.address}}" line="{{ ansible_default_ipv4.address}} {{ inventory_hostname }}"
  notify: restart networking

- name: change ipv6 hosts
  lineinfile: dest=/etc/hosts regexp="^{{ ansible_default_ipv6.address}}" line="{{ ansible_default_ipv6.address}} {{ inventory_hostname }}"
  notify: restart networking

- name: Copy iptables rules file
  copy: src=iptables.up.rules dest=/etc/network/iptables.up.rules
  notify: restart server
  
- name: Ensure iptables is loaded on startup by adding a file to systemd/system
  copy: src=router-rules.service dest=/etc/systemd/system/router-rules.service
  



